by tofalr
CPP-EDU-PROJECTS/MyFilePrinter pull request #2
Opened 2024-07-13 19:30 UTC by ToflarIC

2024-07-13 20:29 UTC, ToflarIC commented
> _ No description provided. _

2024-07-19 08:34 UTC, PawKorchagin requested changes
все норм, только исправь -d для английских букв

2024-07-19 08:34 UTC, PawKorchagin commented on main.cpp
> +    while (std::getline(file, line, opt.delimiter)) {
делимитер правильно срабатывает, но "съедает" все символы ввода, которые ему равны, при выводе тебе в конце каждой строки (которые разделяются делиметром) нужно добавлять opt.delimiter в конец строки.

2024-07-19 08:34 UTC, PawKorchagin commented on main.cpp
> +                            std::cerr << "This argument is not available" << std::endl;
сделай так, чтобы еще латинские буквы a...zA...Z были доступны для делиметра

2024-07-19 08:34 UTC, PawKorchagin commented on main.cpp
> +                opt.name_file = args[i];
надо бы добавить проверку, что у тебя названием файла может быть только один аргумент командной строки, или:

Определи для себя, разрешено ли писать название файла в любом месте командной строки, или только в конце, или вообще можно писать сколько угодно названий файлов где угодно и все они будут выводиться по очереди (можешь отойти от ТЗ в этом месте)

2024-07-19 08:34 UTC, PawKorchagin commented on main.cpp
> +                    if (i + 1 < args.size()) {
Старайся писать комменты не на русском, а самыми простыми словами на английском (в Present Simple), потому что на гитхабе не отображается кодировка нормально, не стесняйся писать комменты на английском, ты просто еще не видел репозитории индусов...

2024-07-19 08:34 UTC, PawKorchagin commented on main.cpp
> +            for (int i = 0; i < opt.lines; ++i) {
у меня segmentation fault ошибка (разберем на занятии), если попытаться вывести пустой файл

2024-07-19 08:34 UTC, PawKorchagin commented on main.cpp
> +                                opt.delimiter = args[i][12];
args[i + 1][0]

2024-07-25 19:57 UTC, merged